language: python

python:
  - 3.6
  
install:
  - pip install -r requirements.txt
  
script:
  - cd apiv1
  - nosetests --with-coverage --cover-package=routes tests/*
  
after_success: 
  - coveralls
